### ISSUE TITLE
loading module if_rtwn_usb fails on FreeBSD 11.0-RELEASE

### ISSUE THREAD

**Issue by benz0li** [s3erios/rtwn#1]
Following the How-to-build and How-to-test according to README.md I was able to successfully build and install the firmware, main module and bus-specific modules.

The modules if_rtwn and if_rtwn_pci load without problems but the execution of `kldload if_rtwn_usb` fails with the following error:
> link_elf_obj: symbol r21au_newstate undefined

The following modules have been moved from /boot/kernel before testing the driver:
* if_rtwn.ko
* if_urtwn.ko
* rtwn-rtl8192cfwU.ko
* rtwn-rtl8192cfwU_B.ko

**Comment by s3erios** [comment]
Fixed, thanks!

**Comment by benz0li** [comment]
Thanks for the great work on the driver. I will do some more testing as soon as I receive the Edimax EW-7811UTC.

**Comment by benz0li** [comment]
The Edimax EW-7811UTC has successfully connected to my 802.11n (5 GHz) network. I haven't tested it with 802.11ac networks - is this supposed to work?

Info for Apple users: It only connects to an Airport Extreme 802.11n (5 GHz) network if the channel is fixed to 48 and not set to automatic (default).
