### ISSUE TITLE
Not support EDUP EP-AC1620

### ISSUE THREAD

**Issue by ykla** [s3erios/rtwn#4]
I have an USB Wireless Dual-Band USB Adapter EDUP EP-AC 1620 which is using rtl8812AU_8821AU. But I cannot using it.

dmesg:
`ugen1.3: <Realtek 802.11ac WLAN Adapter> at usbus1`
```
root@test:~ # sysctl net.wlan.devices
net.wlan.devices: 
```

Both of FreeBSD 12 and 13.
Thanks.

**Comment by s3erios** [comment]
Can you provide vendor / product id for this card? You can show them via
usbconfig dump_device_desc
idVendor / idProduct fields

**Comment by ykla** [comment]
```
ugen0.5: <Realtek 802.11ac WLAN Adapter> at usbus0, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)

  bLength = 0x0012 
  bDescriptorType = 0x0001 
  bcdUSB = 0x0210 
  bDeviceClass = 0x0000  <Probed by interface class>
  bDeviceSubClass = 0x0000 
  bDeviceProtocol = 0x0000 
  bMaxPacketSize0 = 0x0040 
  idVendor = 0x0bda 
  idProduct = 0x0811 
  bcdDevice = 0x0200 
  iManufacturer = 0x0001  <Realtek >
  iProduct = 0x0002  <802.11ac WLAN Adapter >
  iSerialNumber = 0x0003  <00e04c000001>
  bNumConfigurations = 0x0001 

```

**Comment by s3erios** [comment]
Committed in r343518; can you check if it actually works? (it should, but just in case...)

**Comment by ykla** [comment]
It works well now. Thanks a lot.
