### ISSUE TITLE
Add support for TP-Link TL-WN823N v3 

### ISSUE THREAD

**Issue by DomenicoCasillo** [s3erios/rtwn#5]
On FreeBSD 11.2 (opnsense) i've just compiled the current version of the driver but it's not recognizing the device.

ugen3.3: <Realtek 802.11n NIC> at usbus3, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)

  bLength = 0x0012
  bDescriptorType = 0x0001
  bcdUSB = 0x0210
  bDeviceClass = 0x0000  <Probed by interface class>
  bDeviceSubClass = 0x0000
  bDeviceProtocol = 0x0000
  bMaxPacketSize0 = 0x0040
  idVendor = 0x2357
  idProduct = 0x0109
  bcdDevice = 0x0200
  iManufacturer = 0x0001  <Realtek >
  iProduct = 0x0002  <802.11n NIC >
  iSerialNumber = 0x0003  <00e04c000001>
  bNumConfigurations = 0x0001

Can you add support for it?
The dongle is working fine on debian:
[19697.901533] usb 1-2: RTL8192EU rev B (SMIC) 2T2R, TX queues 3, WiFi=1, BT=0, GPS=0, HI PA=0
[19697.901534] usb 1-2: RTL8192EU MAC: d0:37:45:4e:dc:68
[19697.901536] usb 1-2: rtl8xxxu: Loading firmware rtlwifi/rtl8192eu_nic.bin
[19697.901947] usb 1-2: Firmware revision 19.0 (signature 0x92e1)

Thank You.

**Comment by s3erios** [comment]
RTL8192EU support was added directly into the FreeBSD driver version; and, since 11.2 support is discontinued I don't think it's a good idea to backport it here.
(Also I saw this issue too late, so I'm not even sure if it's still actual).

**Comment by illiliti** [comment]
TP-Link TL-WN823N v3 doesn't work according to https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=258018
