### ISSUE TITLE
Not support Foxconn WFUR6

### ISSUE THREAD

**Issue by klewerus** [s3erios/rtwn#6]
I have an USB WIFI Card Foxconn WFUR6,
RTL8812AU-VS 2.4GHz+5GHz ( http://en.techinfodepot.shoutwiki.com/wiki/Foxconn_WFUR6 )

But I can't use it:
root@test# sysctl net.wlan.devices
net.wlan.devices:

Both of FreeBSD 12.1 and 13.

root@test# usbconfig -u 0 -a 4 dump_all_desc
ugen0.4: <Realtek 802.11n NIC> at usbus0, cfg=0 md=HOST spd=HIGH (480Mbps) pwr=ON (500mA)
  bLength = 0x0012
  bDescriptorType = 0x0001
  bcdUSB = 0x0200
  bDeviceClass = 0x0000  <Probed by interface class>
  bDeviceSubClass = 0x0000
  bDeviceProtocol = 0x0000
  bMaxPacketSize0 = 0x0040
  idVendor = 0x0bda
  idProduct = 0x881a
  bcdDevice = 0x0000
  iManufacturer = 0x0001  <Realtek>
  iProduct = 0x0002  <802.11n NIC>
  iSerialNumber = 0x0003  <123456>
  bNumConfigurations = 0x0001

Thanks.

**Comment by klewerus** [comment]
https://svnweb.freebsd.org/base?view=revision&revision=360848
It works well now.

**Comment by cristian-ciobanu** [comment]
@klewerus can you provide me a link where you bought this card ? Is this the same card https://www.aliexpress.com/item/4000617905029.html?spm=a2g0o.placeorder.0.0.584b321eyRgeUk&mp=1 which is USB 2.0 based ?
I have this board https://ae01.alicdn.com/kf/Hd98aecc3fcdf43d092b2f856e3e2e17ca.jpg and I want to know it this card should work in the usb wifi / wwan slot.
Thanks.

**Comment by cristian-ciobanu** [comment]
@klewerus Does this work on FreeBSD 12.1 also ? Can you please provide a working configuration and some steps ?
Thank you.

**Comment by klewerus** [comment]
@cioby23 Yes, this is the same card from Aliexpress. And board - looks similar.
Works only on FreeBSD 12 STABLE, not work on FreeBSD 12.1.

**Comment by cristian-ciobanu** [comment]
@klewerus Thanks I have ordered a piece of this card.
Sorry I'm not very familiar with FreeBSD but version 12.1 isn't newer than 12 stable ? How come this board works on 12 and not on 12.1 ?
I have an board with pfSense 2.5 image on it which is on 12.1 and want to use it.

**Comment by klewerus** [comment]
Card not work on FreeBSD 12.1. Must work on future release FreeBSD 12.2 - https://www.freebsd.org/releases/12.2R/schedule.html
