### ISSUE TITLE
Issue with compiling - "'if_maddr_rlock' declared here"

### ISSUE THREAD

**Issue by unix-vokar** [s3erios/rtwn#7]
Have issue on:

Build and install main module:
cd ../rtwn && make depend && make && make install.

----------------------------------------------------------------------------------------------------------------------------------------------------------

/usr/home/cziken/.github/rtwn/sys/modules/rtwn/../../dev/rtwn/if_rtwn_rx.c:336:4: error: implicit declaration of function 'if_maddr_rlock' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        if_maddr_rlock(ifp);
                        ^
/usr/home/cziken/.github/rtwn/sys/modules/rtwn/../../dev/rtwn/if_rtwn_rx.c:351:4: error: implicit declaration of function 'if_maddr_runlock' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
                        if_maddr_runlock(ifp);
                        ^
/usr/home/cziken/.github/rtwn/sys/modules/rtwn/../../dev/rtwn/if_rtwn_rx.c:351:4: note: did you mean 'if_maddr_rlock'?
/usr/home/cziken/.github/rtwn/sys/modules/rtwn/../../dev/rtwn/if_rtwn_rx.c:336:4: note: 'if_maddr_rlock' declared here
                        if_maddr_rlock(ifp);
                        ^
2 errors generated.
*** Error code 1

Stop.

**Comment by s3erios** [comment]
The compilation issue should be resolved now; however, this repository is not maintained anymore since the driver was already merged to FreeBSD few years ago.

**Comment by mrPsycho** [comment]
hm... if it is merged to FreeBSD... why it is not so easy to find it on FreeBSD 13 nowadays?

looks like will continue to find this repo time to time )
